### ISSUE TITLE
How you label the dataset for Yolov5 training?

### ISSUE THREAD

**Issue by ghost** [Amizorach/FruitSyntheticDataset#1]
Great work. how you label the images and save them in a .txt file?

**Comment by Amizorach** [comment]
I did not need to do this - simply follow the tutorial and when creating the Roboflow dataset you will enter the different (1) labels

If you want to create your own dataset it is not difficult but will demand an understanding of how it's done. This is out of this scope

**Comment by ghost** [comment]
Thanks for the reply. like you draw bounding box yourself, or just you give file and roboflow create yolov5 format dataset ?

**Comment by Amizorach** [comment]
You give them the bounding box that is created by the code. If you want to
visualize it you can unmark the part in the code that will do that for you.
