### ISSUE TITLE
How to change blob size or increase it?

### ISSUE THREAD

**Issue by ghost** [Amizorach/FruitSyntheticDataset#2]
I want to change blob size and also want to generate 2000 images how can i do that?

**Comment by Amizorach** [comment]
Hi.
I will try to send you an answer tomorrow night 😂

**Comment by ghost** [comment]
Okay thanks, and also you label it using Roboflow for yolov5 .txt files or annotated is generated by using this code?

**Comment by hammadyounas2008** [comment]
waiting for your response

**Comment by ghost** [comment]
Hi, I hope you are doing well? Can you please let me know about it?

**Comment by ghost** [comment]
Hello Sorry to disturb you again? Can you please Show me how it perform?

**Comment by Amizorach** [comment]
Sorry for the delay was very busy this week

to create more images (2000) you can simply change the command using -c 2000
You can see the option using -h

the blob size can easily be changed in fruit_dataset_creator.py

it is defined in
def create_bg(colors, width, height):
    im_bg = Image.new('RGBA', (width, height),
ImageColor.getrgb('#7FCBFDFF'))
    draw_bg = ImageDraw.Draw(im_bg)
    plot_random_blobs(draw_bg, colors, 1500, 10, 25)
    im_bg = im_bg.filter(ImageFilter.GaussianBlur())
    return im_bg

def create_fg(colors, width, height):
    im_fg = Image.new('RGBA', (width, height), (0, 0, 0, 0))
    draw_fg = ImageDraw.Draw(im_fg)
    plot_random_blobs(draw_fg, colors, 40, 10, 25)
    im_fg = im_fg.filter(ImageFilter.MedianFilter(size=9))
    return im_fg

Kind regards

**Comment by ghost** [comment]
How to change color of orange, for example, I have green orange how can I change color for that?
